/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banxico/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BanxicoController_validateCep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocr/dataset-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OcrController_findDatasetCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WhatsappController_verifyWebhook"];
        put?: never;
        post: operations["WhatsappController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PropertiesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PropertiesController_remove"];
        options?: never;
        head?: never;
        patch: operations["PropertiesController_update"];
        trace?: never;
    };
    "/properties/{propertyId}/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PropertiesController_getTenants"];
        put?: never;
        post: operations["PropertiesController_createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PropertiesController_removeTenant"];
        options?: never;
        head?: never;
        patch: operations["PropertiesController_updateTenant"];
        trace?: never;
    };
    "/tenants/{id}/fiscal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["TenantsController_updateFiscal"];
        trace?: never;
    };
    "/tenants/{id}/period-adjustment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TenantsController_setPeriodAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{id}/period-adjustment/{billingPeriod}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TenantsController_removePeriodAdjustment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{id}/period-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TenantsController_getPeriodAdjustmentsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSubscriptionsController_findPlans"];
        put?: never;
        post: operations["AdminSubscriptionsController_createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminSubscriptionsController_updatePlan"];
        trace?: never;
    };
    "/admin/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSubscriptionsController_findSubscriptions"];
        put?: never;
        post: operations["AdminSubscriptionsController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminSubscriptionsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AdminSubscriptionsController_update"];
        trace?: never;
    };
    "/admin/subscriptions/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminSubscriptionsController_findPayments"];
        put?: never;
        post: operations["AdminSubscriptionsController_registerPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ManualPaymentsController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/manual/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ManualPaymentsController_validateReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/manual/attempts/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ManualPaymentsController_completeValidation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/manual/balance/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ManualPaymentsController_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/manual/attempts/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ManualPaymentsController_review"];
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/metrics/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_getOcrMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_findAll"];
        put?: never;
        post: operations["LandlordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getAllTenantsAcrossLandlords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/admin/business-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getBusinessMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["LandlordsController_remove"];
        options?: never;
        head?: never;
        patch: operations["LandlordsController_update"];
        trace?: never;
    };
    "/landlords/{id}/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getAllTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LandlordsController_getProperties"];
        put?: never;
        post: operations["LandlordsController_createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FacturasController_findAll"];
        put?: never;
        post: operations["FacturasController_issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FacturasController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FacturasController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}/facturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FacturasController_byLandlord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landlords/{id}/fiscal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FacturasController_updateLandlordFiscal"];
        trace?: never;
    };
    "/tenants/{id}/facturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FacturasController_byTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{id}/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_sendReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/impersonate/{landlordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_impersonate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidateCepDto: {
            claveRastreo: string;
            bancoEmisor: string;
        };
        OcrDatasetCase: {
            id: number;
            attemptId: string;
            methodUsed: string | null;
            rawText: string | null;
            originalExtraction: {
                [key: string]: unknown;
            };
            correctedValues: {
                [key: string]: unknown;
            };
            correctedFields: string[];
            source: string;
            /** Format: date-time */
            createdAt: string;
        };
        Tenant: {
            /**
             * Format: date
             * @example 2026-08-01
             */
            contractStartDate: string | null;
            /**
             * Format: date
             * @example 2027-08-01
             */
            contractEndDate: string | null;
            /**
             * Format: date
             * @example 2026-09-01
             */
            adjustmentDate: string | null;
            id: string;
            name: string;
            phone: string;
            propertyId: string;
            destinationAccount: string;
            destinationAccountType: string;
            paymentDay: number;
            graceDays: number | null;
            monthlyAmount: number;
            rfc: string;
            taxRegime: string;
            zipCode: string;
            nextMonthlyAmount: number | null;
            /** Format: date-time */
            lastReminderAt: string | null;
            /** Format: date-time */
            deletedAt: string | null;
            property: components["schemas"]["Property"];
        };
        Property: {
            id: string;
            name: string;
            landlordId: string;
            landlord: components["schemas"]["Landlord"];
            tenants: components["schemas"]["Tenant"][];
        };
        Landlord: {
            id: string;
            name: string;
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
            isActive: boolean;
            ownerBank: string;
            beneficiaryAccount: string;
            beneficiaryAccountType: string;
            rfc: string;
            taxRegime: string;
            zipCode: string;
            fiscalName: string;
            facturasEnabled: boolean;
            autoRemindersEnabled: boolean;
            defaultReminderDays: number;
            defaultGraceDays: number;
            notifyOnPayment: boolean;
            notifyOnOverdue: boolean;
            properties: components["schemas"]["Property"][];
        };
        UpdatePropertyDto: {
            name?: string;
        };
        CreateTenantDto: {
            name: string;
            phone: string;
            destinationAccount?: string;
            destinationAccountType?: string;
            paymentDay?: number;
            graceDays?: number | null;
            monthlyAmount?: number;
            contractStartDate?: string;
            contractEndDate?: string;
            nextMonthlyAmount?: number;
            adjustmentDate?: string;
        };
        UpdateTenantDto: {
            name?: string;
            phone?: string;
            destinationAccount?: string;
            destinationAccountType?: string;
            paymentDay?: number;
            graceDays?: number | null;
            monthlyAmount?: number;
            contractStartDate?: string;
            contractEndDate?: string;
            nextMonthlyAmount?: number;
            adjustmentDate?: string;
            rfc?: string;
            taxRegime?: string;
            zipCode?: string;
        };
        UpdateTenantFiscalDto: {
            rfc?: string;
            taxRegime?: string;
            zipCode?: string;
        };
        SetPeriodAdjustmentDto: {
            billingPeriod: string;
            expectedAmount: number;
            reason?: string;
        };
        TenantPeriodAdjustment: {
            id: string;
            tenantId: string;
            billingPeriod: string;
            expectedAmount: number;
            reason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Plan: {
            id: string;
            name: string;
            minTenants: number;
            maxTenants: number | null;
            pricePerTenant: number;
            description: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePlanDto: {
            name: string;
            minTenants: number;
            maxTenants?: number | null;
            pricePerTenant: number;
            description?: string;
            isActive?: boolean;
        };
        UpdatePlanDto: {
            name?: string;
            minTenants?: number;
            maxTenants?: number | null;
            pricePerTenant?: number;
            description?: string;
            isActive?: boolean;
        };
        AssignSubscriptionDto: {
            /** Format: uuid */
            landlordId: string;
            contractedTenants: number;
            /** Format: uuid */
            planId?: string;
            /** @enum {string} */
            status?: "ACTIVA" | "VENCIDA" | "CANCELADA" | "CORTESIA";
            startDate?: string;
            months?: number;
            notes?: string;
        };
        LandlordSubscription: {
            id: string;
            landlordId: string;
            landlord: components["schemas"]["Landlord"];
            planId: string;
            plan: components["schemas"]["Plan"];
            contractedTenants: number;
            monthlyAmount: number;
            /** @enum {string} */
            status: "ACTIVA" | "VENCIDA" | "CANCELADA" | "CORTESIA";
            currentPeriodStart: string;
            currentPeriodEnd: string;
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateSubscriptionDto: {
            contractedTenants?: number;
            /** Format: uuid */
            planId?: string;
            /** @enum {string} */
            status?: "ACTIVA" | "VENCIDA" | "CANCELADA" | "CORTESIA";
            currentPeriodEnd?: string;
            notes?: string;
        };
        RegisterSubscriptionPaymentDto: {
            amount?: number;
            paidAt?: string;
            billingPeriod?: string;
            notes?: string;
        };
        SubscriptionPayment: {
            id: string;
            subscriptionId: string;
            subscription: components["schemas"]["LandlordSubscription"];
            landlordId: string;
            billingPeriod: string;
            amount: number;
            paidAt: string;
            recordedBy: string;
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PaymentAttempt: {
            id: string;
            tenantPhone: string;
            tenantId: string;
            tenant: components["schemas"]["Tenant"];
            whatsappMessageId: string;
            imageMediaId: string;
            /** @enum {string} */
            status: "VERIFIED" | "REJECTED" | "ERROR" | "REVIEW" | "PENDING" | "ABANDONED" | "MANUAL_VERIFIED" | "PARTIAL";
            /** @enum {string} */
            source: "WHATSAPP" | "MANUAL";
            amount: number | null;
            /** @enum {string} */
            paymentMethod: "TRANSFERENCIA" | "EFECTIVO" | "DEPOSITO" | "OTRO";
            paymentDate: string;
            billingPeriod: string;
            note: string;
            verifiedOnFirstTry: boolean;
            claveRastreo: string | null;
            ocrData: {
                [key: string]: unknown;
            };
            cepResponse: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: string;
            events: components["schemas"]["PaymentEvent"][];
        };
        PaymentEvent: {
            id: string;
            attemptId: string;
            /** @enum {string} */
            event: "MEDIA_RECEIVED" | "TEXT_WITH_DATA" | "OCR_SUCCESS" | "OCR_FAILED" | "FIELD_REQUESTED" | "FIELD_PROVIDED" | "CEP_CALLED" | "VERIFIED" | "REJECTED" | "CEP_GEMINI_RETRY" | "ERROR" | "REVIEW" | "MANUAL_REGISTERED" | "RECEIPT_UPLOADED" | "MANUAL_REVIEW" | "CANCELLED_BY_TENANT";
            data: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            attempt: components["schemas"]["PaymentAttempt"];
        };
        CreateLandlordDto: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            password: string;
            ownerBank?: string;
            beneficiaryAccount?: string;
            beneficiaryAccountType?: string;
            facturasEnabled?: boolean;
        };
        UpdateLandlordDto: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            password?: string;
            ownerBank?: string;
            beneficiaryAccount?: string;
            beneficiaryAccountType?: string;
            facturasEnabled?: boolean;
            autoRemindersEnabled?: boolean;
            defaultReminderDays?: number;
            defaultGraceDays?: number;
            notifyOnPayment?: boolean;
            notifyOnOverdue?: boolean;
        };
        CreatePropertyDto: {
            name: string;
        };
        CreateFacturaDto: {
            /** Format: uuid */
            landlordId: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            paymentAttemptId?: string;
            billingPeriod?: string;
            amount?: number;
            concepto?: string;
        };
        Factura: {
            id: string;
            landlordId: string;
            landlord: components["schemas"]["Landlord"];
            tenantId: string;
            tenant: components["schemas"]["Tenant"];
            paymentAttemptId: string;
            paymentAttempt: components["schemas"]["PaymentAttempt"];
            uuidCfdi: string;
            serie: string;
            folio: string;
            subtotal: number;
            iva: number;
            total: number;
            concepto: string;
            billingPeriod: string;
            /** @enum {string} */
            status: "ERROR" | "DRAFT" | "STAMPED" | "CANCELLED";
            xmlUrl: string;
            pdfUrl: string;
            xmlContent: string;
            emisorSnapshot: {
                [key: string]: unknown;
            };
            receptorSnapshot: {
                [key: string]: unknown;
            };
            providerResponse: {
                [key: string]: unknown;
            };
            errorMessage: string;
            /** Format: date-time */
            stampedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CancelFacturaDto: {
            /** @enum {string} */
            motivo: "01" | "02" | "03" | "04";
            /** Format: uuid */
            uuidSustitucion?: string;
        };
        CancelacionFactura: {
            id: string;
            facturaId: string;
            factura: components["schemas"]["Factura"];
            /** @enum {string} */
            motivo: "01" | "02" | "03" | "04";
            uuidSustitucion: string;
            /** @enum {string} */
            status: "REJECTED" | "ERROR" | "PENDING" | "ACCEPTED";
            providerResponse: {
                [key: string]: unknown;
            };
            errorMessage: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateLandlordFiscalDto: {
            rfc: string;
            taxRegime: string;
            zipCode: string;
            fiscalName?: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        ForgotPasswordDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            token: string;
            password: string;
        };
        PeriodBalanceDto: {
            tenantId: number;
            tenantName: string;
            /**
             * @description Periodo YYYY-MM
             * @example 2026-07
             */
            period: string;
            expected: number | null;
            paid: number;
            remaining: number | null;
            /** @enum {string} */
            status: "PAGADO" | "PARCIAL" | "PENDIENTE" | "SIN_RENTA_CONFIGURADA";
            attempts: components["schemas"]["PaymentAttempt"][];
        };
        ReportSummaryDto: {
            totalCobrado: number;
            totalPendiente: number;
            cobradoCount: number;
            /** @description Dentro de su plazo (día de pago + gracia) */
            vigenteCount: number;
            /**
             * @deprecated
             * @description Alias de vigenteCount
             */
            pendienteCount: number;
            /** @description Se le acabó la gracia y el mes sigue corriendo */
            atrasadoCount: number;
            /** @description El mes cerró sin pago */
            vencidoCount: number;
            totalTenants: number;
            verifiedOnFirstTryCount: number;
        };
        ReportPropertyDto: {
            propertyId: number;
            propertyName: string;
            totalCobrado: number;
            cobradoCount: number;
            vigenteCount: number;
            /**
             * @deprecated
             * @description Alias de vigenteCount
             */
            pendienteCount: number;
            atrasadoCount: number;
            vencidoCount: number;
            totalTenants: number;
            /** @description 0–100 */
            paidPercent: number;
        };
        ReportTenantRowDto: {
            tenantId: number;
            tenantName: string;
            phone: string;
            propertyId: number;
            propertyName: string;
            paymentDay: number | null;
            monthlyAmount: number | null;
            /** @enum {string} */
            paymentStatus: "Pagado" | "Vigente" | "Atrasado" | "Vencido";
            /** Format: date-time */
            lastVerifiedAt: string | null;
            amountPaid: number | null;
            attemptsCount: number;
        };
        ReportTrendPointDto: {
            /** @example 2026-07 */
            month: string;
            totalCobrado: number;
            cobradoCount: number;
        };
        LandlordReportDto: {
            /**
             * @description Periodo YYYY-MM
             * @example 2026-07
             */
            month: string;
            summary: components["schemas"]["ReportSummaryDto"];
            byProperty: components["schemas"]["ReportPropertyDto"][];
            byTenant: components["schemas"]["ReportTenantRowDto"][];
            monthlyTrend: components["schemas"]["ReportTrendPointDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BanxicoController_validateCep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCepDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OcrController_findDatasetCases: {
        parameters: {
            query?: {
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrDatasetCase"][];
                };
            };
        };
    };
    WhatsappController_verifyWebhook: {
        parameters: {
            query: {
                "hub.mode": string;
                "hub.verify_token": string;
                "hub.challenge": string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    WhatsappController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-hub-signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
        };
    };
    PropertiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePropertyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
        };
    };
    PropertiesController_getTenants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"][];
                };
            };
        };
    };
    PropertiesController_createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
        };
    };
    PropertiesController_removeTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PropertiesController_updateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
        };
    };
    TenantsController_updateFiscal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantFiscalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
        };
    };
    TenantsController_setPeriodAdjustment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPeriodAdjustmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPeriodAdjustment"];
                };
            };
        };
    };
    TenantsController_removePeriodAdjustment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                billingPeriod: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_getPeriodAdjustmentsHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPeriodAdjustment"][];
                };
            };
        };
    };
    AdminSubscriptionsController_findPlans: {
        parameters: {
            query?: {
                includeInactive?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
        };
    };
    AdminSubscriptionsController_createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    AdminSubscriptionsController_updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    AdminSubscriptionsController_findSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    AdminSubscriptionsController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignSubscriptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandlordSubscription"];
                };
            };
        };
    };
    AdminSubscriptionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminSubscriptionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandlordSubscription"];
                };
            };
        };
    };
    AdminSubscriptionsController_findPayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPayment"][];
                };
            };
        };
    };
    AdminSubscriptionsController_registerPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSubscriptionPaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ManualPaymentsController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ManualPaymentsController_validateReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ManualPaymentsController_completeValidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ManualPaymentsController_balance: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ManualPaymentsController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findAll: {
        parameters: {
            query?: {
                phone?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttempt"][];
                };
            };
        };
    };
    PaymentsController_getOcrMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAttempt"];
                };
            };
        };
    };
    PaymentsController_getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LandlordsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landlord"][];
                };
            };
        };
    };
    LandlordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLandlordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landlord"];
                };
            };
        };
    };
    LandlordsController_getAllTenantsAcrossLandlords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    LandlordsController_getBusinessMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LandlordsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landlord"];
                };
            };
        };
    };
    LandlordsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LandlordsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLandlordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landlord"];
                };
            };
        };
    };
    LandlordsController_getAllTenants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    LandlordsController_getReport: {
        parameters: {
            query?: {
                month?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LandlordsController_getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    LandlordsController_getProperties: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"][];
                };
            };
        };
    };
    LandlordsController_createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
        };
    };
    FacturasController_findAll: {
        parameters: {
            query?: {
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factura"][];
                };
            };
        };
    };
    FacturasController_issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFacturaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factura"];
                };
            };
        };
    };
    FacturasController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factura"];
                };
            };
        };
    };
    FacturasController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelFacturaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelacionFactura"];
                };
            };
        };
    };
    FacturasController_byLandlord: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factura"][];
                };
            };
        };
    };
    FacturasController_updateLandlordFiscal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLandlordFiscalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landlord"];
                };
            };
        };
    };
    FacturasController_byTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Factura"][];
                };
            };
        };
    };
    NotificationsController_sendReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_impersonate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landlordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
